template: true
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:

  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: {{ .Values.snapshotRepo }}
          deployerReleaseRepo: {{ .Values.releaseRepo }}
          inputResources:
            - name: mvn_repo
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: build_info

      - name: security_scan
        type: XrayScan
        configuration:
          failOnScan: true
          inputResources:
            - name: build_info
          execution:
            onStart:
              - echo "Preparing for work..."
              - echo "Prepping build environment"
            onSuccess:
              - echo "Job well done!"
            onFailure:
              - echo "uh oh, something went wrong"
            onComplete: #always
              - echo "Cleaning up some stuff"